### ISSUE TITLE
English as Second Language

### ISSUE THREAD

**Issue by CrescendoMeow** [CrescendoMeow/no_more_tweet#5]
03/02/2022-a 我今天才把curriculum (课程)这个单词同CV (curriculum vitae)联系起来。
03/02/2022-b 当我认识assimilate (同化)这个单词之后，突然觉得similar和simulate这两个单词之间应该有某种微妙的关系。另，我总是会念混simulate和stimulate.
03/03/2022-a 学了两个新词，i.e. gentrification (士绅化) vs influencerization (网红化).
03/03/2022-b 我今天才意识到，scrambled egg是炒蛋，fried egg是煎蛋。
03/04/2022-a 学了一个新词，i.e. garment (成衣)，应该算是clothes的单数说法吧。
03/04/2022-b 我今天才知 **格鲁吉亚** 和 **佐治亚州** 在英语里都对应同一个单词Georgia.
03/06/2022-a 总是记不住这几个formatting相关的单词，i.e. *italic*, **bold**, ~~strikethrough~~
03/07/2022-a 总是分不清 bifurcate (分岔) 和 bureaucracy (官僚主义)，明明这两个词长得也不怎么像呀...
03/07/2022-b 学了一个新词，i.e. mix-and-match
03/07/2022-c 一直觉得很难在英语里找到一个准确的词来对应汉语里的**加油**。**come up**总给人一种丧丧的感觉；而**go, go, go**或**goal, goal, goal**或**shot, shot, shot**之类总给人一种黄健翔附体的感觉。介于**cheerleader**是**啦啦队长**的意思，或许**cheer up**是个差强人意的译法？另外，看Hamilton音乐剧的时候，学会了一个**rise up**的说法，不过总觉得这个词应该对应四川口音的**雄起**🤦‍♀️
03/07/2022-d 学了一个新句子，i.e. [The world is your oyster](https://nosweatshakespeare.com/quotes/famous/the-worlds-your-oyster/).
03/08/2022-a 学了一个新句子，i.e. [Birds of a feather flock together](https://en.wikipedia.org/wiki/Birds_of_a_feather_flock_together).
03/10/2022-a 我今天才注意到，essence和essential的重音不一样。
03/10/2022-b 学了一个新句子，i.e. When the winds of change blow, some people build walls; and others build windmills. 至于这句话到底是中国谚语还是欧洲谚语，[已不可考](https://www.zhihu.com/question/38405324)了。以及学会了“拥抱变化、站在风口上”的英文说法，i.e. spot the trend (or the wind), and ride it.

**Comment by y-ding** [comment]
这个issue功能太好玩了😆

**Comment by y-ding** [comment]
看来brunch吃的不够多😂

**Comment by y-ding** [comment]
今日份新词质量都很高呀，尤其加油段最后的抖机灵十分出彩呢！

**Comment by CrescendoMeow** [comment]
This thread has been moved to the `leisure_reading` repo. Please go there and find the latest updates.
